#! /bin/bash

#*************************************************************************
# "run-tests" is free software: you can redistribute it and/or modify    *
# it under the terms of the GNU Affero Public License as published by    *
# the Free Software Foundation, either version 3 of the License, or      *
# (at your option) any later version.                                    *
#                                                                        *
# "run-tests" is distributed in the hope that it will be useful,         *
# but WITHOUT ANY WARRANTY; without even the implied warranty of         *
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
# GNU Affero Public License for more details.                            *
#                                                                        *
# You should have received a copy of the GNU Affero Public License       *
# along with Edward.  If not, see <http://www.gnu.org/licenses/>.        *
#                                                                        *
# Copyright (C) 2015 Andrew Engelbrecht                     (AGPLv3+)    *
#*************************************************************************

G_HOME=./tests/testgnupghome

OUT_DIFF_1="$(time ./edward < ./tests/test1.eml | GNUPGHOME="$G_HOME" gpg 2> /dev/null | ./tests/flatten-mime | diff -Z -u ./tests/out1.txt - )"

if [ -n "$OUT_DIFF_1" ] ; then
    echo "*** test 1 failed! difference:" >&2
    echo "$OUT_DIFF_1" >&2
fi

